### ISSUE TITLE
`replace` and `replaceAll` should allow op2 to be white-space

### ISSUE THREAD

**Issue by pinkasey** [mbaersch/number-string-operations#1]
I came across this template when I had a simple need -
I needed to convert all the spaces in a variable to `_`.

When I try to use `replace` or `replaceAll`,
if I put ` ` (a single space) as op2 - I get an error saying:
`The value must not be empty.`

![image](https://user-images.githubusercontent.com/1780369/217805736-3779cec2-c4a6-49e2-beb2-ea531267d257.png)

**Comment by mbaersch** [comment]
you could try to change the template and get rid of the validation rule there, but I expect the editor to "auto trim" the value to be empty again. Additionally, it seems to kill the server if you try to use the template in that way and I guess this happens due to an error when the API sandbox executes the replace function with a value that gets "sanitized" to an empty string. 

However, there seems to be no way of configuring a working parameter field for whitespace input like that. I can try to enhance the template to use regex here without making it even more complex to use but this will take a while. 

In the meantime you can create and use a simple template for this specific task. 

1. add a new variable template and enter a name 
2. add a text input field on the "Fields" tab and call it "textInput" (or keep the name "text1" and adjust the code line below)
3. on the "Code" tab, enter the following code line: `return data.textInput.split(" ").join("_");`
4. save the template and use this to create a variable that converts all spaces from the input value to underscores. 
    
hope that helps

**Comment by pinkasey** [comment]
Wow, thanks @mbaersch !
I didn't expect such elaborate response...

I've since found a workaround for my need, because usually I don't get responses for Issues I open.

I think a `replaceRegex` is the best option here.
Perhaps `replaceSpace` is also a good option.
I might try and open a pull-request for this, I don't promise.
  
Thank you very much for your support!

**Comment by mbaersch** [comment]
yes, please: contribute whenever you find the time and motivation 😉

**Comment by mbaersch** [comment]
closed for now
